bf16: true
bf16_full_eval: true
tf32: true
dataloader_drop_last: true
dataloader_num_workers: 4
dataloader_pin_memory: true
do_eval: false
do_train: true
evaluation_strategy: "steps"
eval_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 4e-4
log_on_each_node: false
logging_steps: 1
lr_scheduler_type: "cosine"
max_grad_norm: 1.0
num_train_epochs: 5
optim: "adamw_torch"
per_device_eval_batch_size: 1024
per_device_train_batch_size: 1024
save_steps: 1000
save_strategy: "steps"
save_total_limit: 5
torch_compile: false
warmup_steps: 1000
weight_decay: 0.01
save_spec_steps: 10000
deepspeed:
  zero_optimization:
    stage: 0
  optimizer:
    type: 'AdamW'
    params:
      lr: 'auto'
      betas: 'auto'
      eps: 'auto'
      weight_decay: 'auto'
  scheduler:
    type: 'WarmupDecayLR'
    params:
      last_batch_iteration: -1
      total_num_steps: 'auto'
      warmup_min_lr: 'auto'
      warmup_max_lr: 'auto'
      warmup_num_steps: 'auto'
  gradient_accumulation_steps: 'auto'
  gradient_clipping: 'auto'
  train_batch_size: 'auto'
  train_micro_batch_size_per_gpu: 'auto'