model_name_or_path: 'llama_flash_attention'
n_ctx: 64
vocab_size: 30003
hidden_size: 640
num_hidden_layers: 24
num_attention_heads: 10
intermediate_size: 2560
_flash_attn_2_enabled: true
bos_token_id: "<bos>"
eos_token_id: "<eos>"