dataset_name: "PubChem"
data_root: "./data/processed/training/"
tokenizer_path: "tokenizers/BPE_pubchem_500.json"
dataset_path: "pubchem/*"
file_type: "parquet"
overwrite_cache: false
max_seq_length: 64
batch_size: 1024
dataloader_num_workers: 4
preprocess_num_workers: 24
folder_url: "https://drive.google.com/drive/folders/1qLFWbdixlIUimdi5brdfXlv3Qiw8UAp3"
validation_size: 0.1
val_split_seed: 42