dataset_name: "MolGen/ZINC_270M"
tokenizer_path: "./data/processed/training/tokenizers/BPE_pubchem_500.json"
column: "SMILES"
overwrite_cache: false
max_seq_length: 64
dataloader_num_workers: 4
preprocess_num_workers: 24
validation_size: 0.1
val_split_seed: 42