dataset_name: "MolGen/ZINC_22-raw"
tokenizer_path: "./data/processed/training/tokenizers/atomwise_ZINC_270M_SMILES_30000.json"
mol_type: "SMILES"
overwrite_cache: false
max_seq_length: 64
dataloader_num_workers: 48
preprocess_num_workers: 48
validation_size: 0.001
val_split_seed: 42