# The Defaults List is a list in an input config that instructs Hydra how to build the output config.

config_name: train_moses_llama
seeds: [42, 1335, 2024]

wandb_logs: false
wandb:
  name: null
  project: small-molecule-generation
  entity: drug-discovery
  tags: []
  mode: online