# The Defaults List is a list in an input config that instructs Hydra how to build the output config.
defaults:
  - _self_
  - dataset: ZINC_270M_smiles_atomwise
  - model: llama-tiny_flash_attention
  - trainer: hf_trainer_FA
  - eval: basic

seed: 42
save_path: './save_new'
write_HF_token: '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'
read_HF_token: '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'

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/hydra

wandb_logs: true
wandb:
  name: null
  project: small-molecule-generation
  entity: drug-discovery
  tags: []
  mode: online